BOARD_VENDOR := samsung
DEVICE_PATH := device/samsung/beyond2lte

# Platform
TARGET_BOARD_PLATFORM := exynos9820
TARGET_SOC := exynos9820
TARGET_BOOTLOADER_BOARD_NAME := beyond2lte

# Recovery
BOARD_HAS_NO_REAL_SDCARD := true
BOARD_SUPPRESS_EMMC_WIPE := true
BOARD_SUPPRESS_SECURE_ERASE := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TW_THEME := portrait_hdpi
TW_DEFAULT_LANGUAGE := en
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_NTFS_3G := true
TW_USE_TOOLBOX := true
TW_INCLUDE_REPACKTOOLS := true
TW_HAS_DOWNLOAD_MODE := true
TW_NO_SCREEN_TIMEOUT := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_EXCLUDE_TWRPAPP := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_INCLUDE_FB2PNG := true
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/recovery.fstab
